# Generated by Django 5.2.7 on 2025-10-12 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleImage',
            fields=[
                ('img_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('img_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzlePiece',
            fields=[
                ('piece_id', models.AutoField(primary_key=True, serialize=False)),
                ('piece_number', models.IntegerField()),
                ('piece_path', models.CharField(max_length=255)),
                ('puzzle_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='hri_app.puzzleimage')),
            ],
        ),
    ]
