# Generated by Django 5.2.7 on 2025-11-06 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRecordDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('puzzle_id', models.CharField(max_length=50)),
                ('piece_id', models.CharField(max_length=5)),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalRecordGeneral',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('team_member', models.CharField(max_length=255)),
                ('game_mode', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=20)),
                ('character', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=20)),
                ('with_ai', models.BooleanField()),
                ('puzzle_amount', models.IntegerField()),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('solved_puzzle_amount', models.IntegerField()),
                ('correct_piece_amount', models.IntegerField()),
                ('wrong_piece_amount', models.IntegerField()),
                ('accuracy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PieceDragLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_id', models.CharField(max_length=50)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleImage',
            fields=[
                ('img_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('img_path', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzlePiece',
            fields=[
                ('piece_id', models.AutoField(primary_key=True, serialize=False)),
                ('piece_number', models.IntegerField()),
                ('piece_path', models.CharField(max_length=255)),
                ('puzzle_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='hri_app.puzzleimage')),
            ],
        ),
    ]
