# Generated by Django 5.2.7 on 2025-10-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hri_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzleimage',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
