# Generated by Django 5.2.7 on 2025-10-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hri_app', '0003_piecedraglog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRecordDetails',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('puzzle_id', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalRecordGeneral',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('team_member', models.CharField(max_length=255)),
                ('game_mode', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=20)),
                ('character', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=20)),
                ('bg_color', models.CharField(max_length=20)),
                ('puzzle_amount', models.IntegerField()),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField(auto_now_add=True)),
                ('self_rate_score', models.IntegerField(default=0)),
                ('ai_rate_score', models.IntegerField(default=0)),
            ],
        ),
    ]
