# Generated by Django 5.2.7 on 2025-10-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hri_app', '0004_personalrecorddetails_personalrecordgeneral'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalRecordDetails',
            new_name='PersonalRecordDetail',
        ),
    ]
