# Generated by Django 5.2.7 on 2025-10-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hri_app', '0005_rename_personalrecorddetails_personalrecorddetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalrecordgeneral',
            old_name='ai_rate_score',
            new_name='ai_task_score',
        ),
        migrations.RenameField(
            model_name='personalrecordgeneral',
            old_name='self_rate_score',
            new_name='self_feeling_score',
        ),
        migrations.AddField(
            model_name='personalrecordgeneral',
            name='self_task_score',
            field=models.IntegerField(default=0),
        ),
    ]
