# Generated by Django 5.2.7 on 2025-10-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hri_app', '0006_rename_ai_rate_score_personalrecordgeneral_ai_task_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalrecordgeneral',
            name='time_end',
            field=models.DateTimeField(),
        ),
    ]
