# Generated by Django 5.2.7 on 2025-10-20 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hri_app', '0007_alter_personalrecordgeneral_time_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalrecordgeneral',
            name='activity',
        ),
    ]
