# Generated by Django 5.2.7 on 2025-10-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hri_app', '0008_remove_personalrecordgeneral_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalrecordgeneral',
            old_name='bg_color',
            new_name='activity',
        ),
    ]
